### ISSUE TITLE
Missing lxml dependency in setup.py

### ISSUE THREAD

**Issue by hqwisen** [mingchen/django-cas-ng#162]
The title says it all.

The **lxml** dependency is set in `requirements.txt` but not in `setup.py`, which fails when calling **/accounts/callback/**.

```
Internal Server Error: /accounts/callback/
Traceback (most recent call last)
   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/lib/python2.7/site-packages/django/views/decorators/http.py", line 42, in inner
     return func(request, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/django_cas_ng/views.py", line 162, in callback
     clean_sessions(get_cas_client(request=request), request)
   File "/usr/lib/python2.7/site-packages/django_cas_ng/views.py", line 177, in clean_sessions
     for slo in client.get_saml_slos(request.POST.get('logoutRequest')):
   File "/usr/lib/python2.7/site-packages/cas.py", line 15, in get_saml_slos
     from lxml import etree
 ImportError: No module named lxml
```

**Comment by mingchen** [comment]
Fixed in e9c0472: Upgrade requirements.txt: python-cas==1.3.0
