### ISSUE TITLE
django-cas-ng 3.6  django2.0.7  启用CAS_VERSION=3下面是报错

### ISSUE THREAD

**Issue by luolin0313** [mingchen/django-cas-ng#192]
ERROR:default:Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python3/lib/python3.6/site-packages/django_cas_ng/views.py", line 39, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django_cas_ng/views.py", line 125, in get
    raise PermissionDenied(_('Login failed.'))
django.core.exceptions.PermissionDenied: Login failed.

**Comment by Nsuidara** [comment]
Ok, problem was with custom User model - here no username ... (i using "email")
but message "PermissionDenied" isnt enought

**Comment by zohrehhanza** [comment]
is there any update for wrappers around django-cas-ng to be compatible with django 2.1+?
@csrf_exempt
def login(request, **kwargs):
    return _add_locale(request, baseviews.login(request, **kwargs))


def logout(request, **kwargs):
    return _add_locale(request, baseviews.logout(request, **kwargs))
