### ISSUE TITLE
Library cannot import its base import function

### ISSUE THREAD

**Issue by chingiz** [mingchen/django-cas-ng#201]
I installed the latest version of library but instead it gives me error inside in its own files.

> +models.py
> +views.py

```
File "/Users/chingizh/PycharmProjects/helpdesk/helpdesk/urls.py", line 23, in <module>
    from django_cas_ng.views import LoginView, LogoutView
File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django_cas_ng/views.py", line 20, in <module>
    from .models import ProxyGrantingTicket, SessionTicket
File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django_cas_ng/models.py", line 4, in <module>
    from cas import CASError
```

**Comment by Chingiz** [comment]
@mingchen can you resolve or suggest anything about this issue? It is still continuing

**Comment by laymonage** [comment]
Could you post the full traceback of the error (or at least the exception raised)?

**Comment by Chingiz** [comment]
This is full traceback
```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chingizh/PycharmProjects/helpdesk/venv/lib/python3.6/site-packages/django_cas_ng/models.py", line 4, in <module>
    from cas import CASError
ImportError: cannot import name 'CASError'
```

**Comment by laymonage** [comment]
Do you have [`django-cas-client`](https://pypi.org/project/django-cas-client/) installed? If yes, try uninstalling it. Refer to #71.
