### ISSUE TITLE
ImportError: cannot import name urllib_parse

### ISSUE THREAD

**Issue by switchtower** [mingchen/django-cas-ng#48]
Hello!

The README states that django-cas-ng supports 1.5 but it appears urllib_parse was introduced in Django 1.6. 

Is there anything that can be done to support 1.5?

Thanks :)

**Comment by bgroff** [comment]
Can you post a stack trace for this? Urllib is shipped as a part of Python and not Django. There are compatibility issues between Py2/Py3 so if you are using Python3 it is possible that that is the reason for your error.

**Comment by mingchen** [comment]
Check the CI builds, there are job for Django 1.5 support. see detail: https://travis-ci.org/mingchen/django-cas-ng

**Comment by adamcharnock** [comment]
I'm receiving this error too, django 1.5.4. Stack trace:

```
$ ./manage.py runserver
Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x109dd1cd0>>
Traceback (most recent call last):
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 92, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/core/management/base.py", line 280, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/core/management/validation.py", line 35, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/db/models/loading.py", line 166, in get_app_errors
    self._populate()
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django_cas_ng/models.py", line 4, in <module>
    from .utils import (get_cas_client, get_service_url, get_user_from_session)
  File "/Users/adam/Envs/banking-check-legacy/lib/python2.7/site-packages/django_cas_ng/utils.py", line 5, in <module>
    from django.utils.six.moves import urllib_parse
ImportError: cannot import name urllib_parse
```

However, it seems this was actually added in Django 1.5.5, so minor version upgrade should sort it.

Hopefully this helps someone else out.
