### ISSUE TITLE
Error while integrating django-cas-ng

### ISSUE THREAD

**Issue by rakheemnair** [mingchen/django-cas-ng#84]
Hi,
I am new to python,  django. But I need to integrate HUE in our system.

We need to use integerate SSO in HUE using CAS.

I have followed the steps given https://pypi.python.org/pypi/django-cas-ng

I am able to login using CAS server. But not getting redirect to my application home page after that.
Getting error like below. Please provide suggestion:

[17/Mar/2016 05:21:51 +0000] middleware   INFO     Processing exception: <urlopen error [Errno 110] Connection timed out>: Traceback (most recent call last):
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/django_cas_ng/views.py", line 60, in login
    request=request)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/django_cas_ng/backends.py", line 23, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/cas.py", line 141, in verify_ticket
    response = self.get_verification_response(ticket)
  File "/home/hue/rakhee/hue/build/env/local/lib/python2.7/site-packages/cas.py", line 150, in get_verification_response
    page = urllib_request.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>

Run ./manage.py syncdb. Is this mandatory?

Regards,
Rakhee

**Comment by mingchen** [comment]
you need create db to cache session.
